// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: 07GUI
#include "Arduino.h"
#include "ui.h"

extern int fahrstufe;
extern int wunschdruckVA;
extern int wunschdruckHA;
extern int druckvaok;
extern int druckhaok;

void fahrstufenaenderung(lv_event_t * e)
{	
if (fahrstufe == 0) 
{wunschdruckVA = 0;
wunschdruckHA = 0;} 
else if (fahrstufe == 1) 
{wunschdruckVA = 14;
wunschdruckHA = 35;}
else if (fahrstufe == 2) 
{wunschdruckVA = 55;
wunschdruckHA = 45;}
else if (fahrstufe == 3) 
{wunschdruckVA = 65;
wunschdruckHA = 57;}
else if (fahrstufe == 4) 
{wunschdruckVA = 99;
wunschdruckHA = 99;}
druckvaok = 0;
druckhaok = 0;
}

void wunschhochVA(lv_event_t * e)
{
if (wunschdruckVA >= 0 && wunschdruckVA < 100) 
{  wunschdruckVA = wunschdruckVA+1;
druckvaok = 0;}
}

void wunschrunterVA(lv_event_t * e)
{
if (wunschdruckVA <= 100 && wunschdruckVA >0) 
{wunschdruckVA = wunschdruckVA-1;
druckvaok = 0;} 
}

void fahrstufehoch(lv_event_t * e)
{
if (fahrstufe >= 0 && fahrstufe <4) 
{fahrstufe = fahrstufe+1;} 
}

void fahrstuferunter(lv_event_t * e)
{if (fahrstufe <= 4 && fahrstufe >0) 
{fahrstufe = fahrstufe-1;} 
}

void wunschhochHA(lv_event_t * e)
{
	if (wunschdruckHA >= 0 && wunschdruckHA <100) 
{wunschdruckHA = wunschdruckHA+1;
druckhaok = 0;}
}

void wunschrunterHA(lv_event_t * e)
{
	if (wunschdruckHA <= 100 && wunschdruckHA >0) 
{wunschdruckHA = wunschdruckHA-1;
druckhaok = 0;} 
}
